### ISSUE TITLE
Add the Caraya 'Define Test' in the Drona palette

### ISSUE THREAD

**Issue by keerthivarman-nageshwaran** [solitontech/SLL-Drona#6]
This helps reduce the switching between the Drona and Caraya palette.

Reported by Sairam

**Comment by kavin1730** [comment]
Solution: Created an API, which contains Caraya Define Test Node. This helps in reducing the switching between Drona and Caraya palette.

![image](https://github.com/solitontech/SLL-Drona/assets/135618969/4c2c5de9-8935-4007-9b8e-a90cc1da5b55)

Define Test:
![image](https://github.com/solitontech/SLL-Drona/assets/135618969/cec65e01-1547-4404-bddf-9cca4273a666)


While building Package, configure the Define test API as "Place VI Contents". This configuration will help to place only the Caraya define test node instead of placing the API on block diagram.

![image](https://github.com/solitontech/SLL-Drona/assets/135618969/cc5f1a0d-c887-4e5d-bf8b-78ec679af556)

**Comment by keerthivarman-nageshwaran** [comment]
@Sairam0496 Can we add setup, assert and close as part of this? (like a Drona template code)

**Comment by kavin1730** [comment]
> I am wondering if the following can be added as a template.
> 
> ![image](https://user-images.githubusercontent.com/100664779/253005536-d4270509-cb33-42aa-a531-32585a5a189b.png)

Added this as a new issue[#50 ]
